version: '2'
services:
  redis:
    restart: always
    image: redis:3.2.8
    ports:
      - "6379:6379"
    networks: 
      - analytics

  logstash:
    restart: always
    build: ./logstash
    ports:
      - "6000:6000/udp"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - analytics
    depends_on: 
      - redis
  
  influx:
    restart: always
    image: influxdb:1.2.2
    ports: 
      - "8083:8083"
      - "8086:8086"
    networks: 
      - analytics

  grafana:
    restart: always
    image: grafana/grafana:4.1.1
    ports:
      - "3000:3000"
    networks: 
      - analytics
    depends_on: 
      - influx
  
networks: 
  analytics:
    driver: bridge
