---

- name: Configure Sensu APT key
  apt_key:
    url: https://sensu.global.ssl.fastly.net/apt/pubkey.gpg
    state: present
  tags:
    - sensu
    - repo

- name: Configure the Sensu APT repositories
  become: yes
  apt_repository:
    repo: "deb https://sensu.global.ssl.fastly.net/apt xenial main"
    state: present
    update_cache: true
  tags:
    - sensu
    - repo

- name: Install Sensu
  apt: pkg=sensu autoremove=yes state=present update_cache=yes

- name: Ensure Sensu config directory exists
  file:
    dest: "{{ sensu_config_path }}/conf.d"
    state: directory
    recurse: true
    owner: "{{ sensu_user_name }}"
    group: "{{ sensu_group_name }}"

- name: Ensure Sensu plugin directory exists
  file:
    dest: "{{ sensu_config_path }}/plugins"
    state: directory
    owner: "{{ sensu_user_name }}"
    group: "{{ sensu_group_name }}"

- name: Install Sensu plugins
  shell: sensu-install -p {{ item }}
  with_items: "{{ sensu_remote_plugins + sensu_plugins }}"
  changed_when: false
  when: sensu_remote_plugins > 0

- name: Install Sensu plugin support gems
  shell: "{{ sensu_path }}/embedded/bin/gem install {{ item }} --no-doc --no-ri"
  become: true
  with_items: "{{ sensu_remote_plugins_gems + sensu_plugins_gems }}"
  changed_when: false
  when: sensu_remote_plugins_gems > 0

- name: Configure Sensu
  template:
    src: "{{ sensu_client_config }}"
    dest: "{{ sensu_config_path }}/conf.d/client.json"
    owner: "{{ sensu_user_name }}"
    group: "{{ sensu_group_name }}"
  notify:
    - Restart Sensu

- name: Register available checks
  local_action: command ls {{ static_data_store }}/sensu/checks
  register: sensu_available_checks
  changed_when: false
  become: false

- name: Deploy check plugins
  copy:
    src: "{{ static_data_store }}/sensu/checks/{{ item }}/"
    dest: "{{ sensu_config_path }}/plugins/"
    mode: 0755
    owner: "{{ sensu_user_name }}"
    group: "{{ sensu_group_name }}"
  when: "sensu_available_checks is defined and '{{ item }}' in sensu_available_checks.stdout_lines"
  with_flattened:
    - "{{ sensu_client_subscriptions }}"
  notify: Restart Sensu

- name: Deploy handler plugins
  copy:
    src: "{{ static_data_store }}/sensu/handlers/"
    dest: "{{ sensu_config_path }}/plugins/"
    mode: 0755
    owner: "{{ sensu_user_name }}"
    group: "{{ sensu_group_name }}"
  notify: Restart Sensu

- name: Deploy filter plugins
  copy:
    src: "{{ static_data_store }}/sensu/filters/"
    dest: "{{ sensu_config_path }}/plugins/"
    mode: 0755
    owner: "{{ sensu_user_name }}"
    group: "{{ sensu_group_name }}"
  notify: Restart Sensu

- name: Deploy mutator plugins
  copy:
    src: "{{ static_data_store }}/sensu/mutators/"
    dest: "{{ sensu_config_path }}/plugins/"
    mode: 0755
    owner: "{{ sensu_user_name }}"
    group: "{{ sensu_group_name }}"
  notify: Restart Sensu

