version: '2'

services:
  db:
    restart: always
    build: ./postgresql
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=admin
      - POSTGRES_DB=rompr
    networks:
      - core

  nats:
    restart: always
    image: nats
    ports:
      - "8222:8222"
      - "6222:6222"
      - "4222:4222"
    networks:
      - core

  filestore:
    restart: always
    image: 017056342716.dkr.ecr.us-east-1.amazonaws.com/filestore:1.1.0
    ports:
      - "7701:80"
    environment:
      - "ConnectionStrings:FileStoreDatabase=User ID=admin;Password=password;Host=db;Port=5432;Database=rompr;Pooling=true;"
    depends_on: 
      - db
    networks:
      - core

networks:
  core:
    driver: bridge