---
- name: Install Redis
  apt: pkg=redis-server={{ redis_version }} state=present

- name: Configure Redis
  template: src=redis.conf.j2 dest=/etc/redis/redis.conf
  notify:
    - Restart Redis


- name: Configure somaxconn
  lineinfile: dest=/etc/sysctl.conf
              regexp='^net.core.somaxconn'
              line='net.core.somaxconn=65535'
              state=present
              create=True

- name: Set somaxconn
  command: sysctl -w net.core.somaxconn=65535

- name: Disable HUGEPAGE
  lineinfile: dest=/etc/rc.local
              regexp='transparent_hugepage'
              line='echo never > /sys/kernel/mm/transparent_hugepage/enabled'
              state=present
              create=True

- name: Set Hugepage disabled
  command: echo never > /sys/kernel/mm/transparent_hugepage/enabled
