---

- name: ElasticSearch Cluster
  hosts: es_nodes
  become: yes
  become_user: root
  remote_user: ubuntu
  vars:
    - sensu_client_subscriptions:
      - linux
      - elasticsearch
    - sensu_plugins:
      - sensu-plugins-elasticsearch
    - update_apt_cache: yes
    - es_scripts: false
    - es_templates: false
    - es_version_lock: false
    - es_enable_xpack: true
    - es_xpack_features:
      - alerting
      - monitoring
      - graph

  vars_files:
    - env_vars/base.yml

  roles:
    - { role: "ycs.base" }
    - { role: "ansible-elasticsearch", es_instance_name: "{{ inventory_hostname }}", es_heap_size: "2g",
      es_config: {
        cluster.name: "es-cluster",
        node.name: "{{ inventory_hostname }}",
        network.host: "_site_, _local_",
        discovery.zen.ping.unicast.hosts: "es-1.corp.rambleron.com:9300",
        http.port: 9200,
        transport.tcp.port: 9300,
        node.data: true,
        bootstrap.memory_lock: true,
        }
    }

